version: '3.1'
services :

  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    networks:
      - db-network

  database-admin:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - db-network

  ## in grafana > data-source set url to http://host.docker.internal:9090
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - "monitoring-network"

  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - "monitoring-network"
    depends_on:
      - prometheus
#      - loki

  ## in grafana > data-source set url to http://host.docker.internal:3100
#  loki:
#    image: grafana/loki:2.1.0
#    command: -config.file=/etc/loki/local-config.yaml
#    ports:
#      - "3100:3100"
#    networks:
#      - monitoring-network
#
#  promtail:
#    image: grafana/promtail:2.0.0
#    volumes:
#      - ./promtail/promtail-config.yaml:/etc/promtail/docker-config.yaml
#      - ./logs/monitoring.log:/var/log/monitoring.log
#    command: "--config.file=/etc/promtail/docker-config.yaml"
#    networks:
#      - monitoring-network

networks:
  db-network:
    driver: bridge
  monitoring-network:
    driver: bridge

volumes:
  grafana-volume:
