version: '3.1'
services :

  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    networks:
      - db-network

  database-admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
