{
 "title": "My Diary",
 "description": "Dashboard for MyDiary application",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "my-diary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mean Time Response",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", status=~\"2..\", uri=~\".*/v.*\"}[$__range])) by (application)\r\n/\r\nsum(rate(http_server_requests_seconds_count{application=\"$application\", status=~\"2..\", uri=~\".*/v.*\"}[$__range])) by (application)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Notes Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ceil(increase(http_server_requests_seconds_sum{application=\"$application\", uri=~\"/v1/my-diary/.*\", status=~\"2..\", method=\"POST\"}[$__range])))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "system_cpu_count{application=\"$application\",instance=\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Request time Http 200",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=~\"/v1/my-diary/.*\", status=\"200\"}[1m]) \r\n/ \r\nrate(http_server_requests_seconds_count{uri=~\"/v1/my-diary/.*\", status=\"200\"}[1m])",
     "legendFormat": "{{uri}} {{method}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"2..\", uri=~\"/v1/my-diary/.*\"}[1m])",
     "legendFormat": "{{uri}} {{method}} {{status}}"
    }
   ]
  }
 ]
}